use std::fmt::Write as _;

use super::raster::arc_pts;
use crate::canvas::draw::{Align, Color, Draw};
use crate::canvas::geom::Rect;

pub struct Svg {
    out: String,
    clip_count: usize,
    clip_stack: Vec<String>,
}

impl Svg {
    pub fn new(scene: Rect) -> Self {
        let mut out = String::new();
        let _ = write!(
            out,
            concat!(
                "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n",
                "<svg xmlns=\"http://www.w3.org/2000/svg\" ",
                "width=\"{w}\" height=\"{h}\" viewBox=\"{x} {y} {vw} {vh}\">\n",
                "<title>Circuit Name</title>\n",
                "<desc>Generated by Circuit Simulator</desc>\n"
            ),
            w = f(scene.w),
            h = f(scene.h),
            x = f(scene.x),
            y = f(scene.y),
            vw = f(scene.w),
            vh = f(scene.h),
        );
        Self {
            out,
            clip_count: 0,
            clip_stack: Vec::new(),
        }
    }

    pub fn finish(mut self) -> String {
        self.out.push_str("</svg>\n");
        self.out
    }

    fn pts(pts: &[[f64; 2]]) -> String {
        pts.iter()
            .map(|p| format!("{},{}", f(p[0]), f(p[1])))
            .collect::<Vec<_>>()
            .join(" ")
    }
}

pub fn f(v: f64) -> String {
    let s = format!("{v:.4}");
    let s = s.trim_end_matches('0').trim_end_matches('.').to_string();
    if s == "-0" { "0".into() } else { s }
}

pub fn xml_escape(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
}

#[allow(clippy::write_with_newline, clippy::too_many_arguments)]
impl Draw for Svg {
    fn fill_rect(&mut self, x: f64, y: f64, w: f64, h: f64, c: Color) {
        let _ = write!(
            self.out,
            "<rect x=\"{}\" y=\"{}\" width=\"{}\" height=\"{}\" fill=\"{}\"/>\n",
            f(x),
            f(y),
            f(w),
            f(h),
            c.css()
        );
    }

    fn stroke_rect(&mut self, x: f64, y: f64, w: f64, h: f64, c: Color, width: f64) {
        let _ = write!(
            self.out,
            "<rect x=\"{}\" y=\"{}\" width=\"{}\" height=\"{}\" fill=\"none\" stroke=\"{}\" stroke-width=\"{}\"/>\n",
            f(x),
            f(y),
            f(w),
            f(h),
            c.css(),
            f(width)
        );
    }

    fn fill_round_rect(&mut self, x: f64, y: f64, w: f64, h: f64, r: f64, c: Color) {
        let _ = write!(
            self.out,
            "<rect x=\"{}\" y=\"{}\" width=\"{}\" height=\"{}\" rx=\"{}\" fill=\"{}\"/>\n",
            f(x),
            f(y),
            f(w),
            f(h),
            f(r),
            c.css()
        );
    }

    fn stroke_round_rect(&mut self, x: f64, y: f64, w: f64, h: f64, r: f64, c: Color, width: f64) {
        let _ = write!(
            self.out,
            "<rect x=\"{}\" y=\"{}\" width=\"{}\" height=\"{}\" rx=\"{}\" fill=\"none\" stroke=\"{}\" stroke-width=\"{}\"/>\n",
            f(x),
            f(y),
            f(w),
            f(h),
            f(r),
            c.css(),
            f(width)
        );
    }

    fn fill_circle(&mut self, cx: f64, cy: f64, r: f64, c: Color) {
        let _ = write!(
            self.out,
            "<circle cx=\"{}\" cy=\"{}\" r=\"{}\" fill=\"{}\"/>\n",
            f(cx),
            f(cy),
            f(r),
            c.css()
        );
    }

    fn stroke_circle(&mut self, cx: f64, cy: f64, r: f64, c: Color, width: f64) {
        let _ = write!(
            self.out,
            "<circle cx=\"{}\" cy=\"{}\" r=\"{}\" fill=\"none\" stroke=\"{}\" stroke-width=\"{}\"/>\n",
            f(cx),
            f(cy),
            f(r),
            c.css(),
            f(width)
        );
    }

    fn fill_ellipse(&mut self, x: f64, y: f64, w: f64, h: f64, c: Color) {
        let _ = write!(
            self.out,
            "<ellipse cx=\"{}\" cy=\"{}\" rx=\"{}\" ry=\"{}\" fill=\"{}\"/>\n",
            f(x + w * 0.5),
            f(y + h * 0.5),
            f(w * 0.5),
            f(h * 0.5),
            c.css()
        );
    }

    fn stroke_ellipse(&mut self, x: f64, y: f64, w: f64, h: f64, c: Color, width: f64) {
        let _ = write!(
            self.out,
            "<ellipse cx=\"{}\" cy=\"{}\" rx=\"{}\" ry=\"{}\" fill=\"none\" stroke=\"{}\" stroke-width=\"{}\"/>\n",
            f(x + w * 0.5),
            f(y + h * 0.5),
            f(w * 0.5),
            f(h * 0.5),
            c.css(),
            f(width)
        );
    }

    fn fill_poly(&mut self, pts: &[[f64; 2]], c: Color) {
        let _ = write!(
            self.out,
            "<polygon points=\"{}\" fill=\"{}\"/>\n",
            Self::pts(pts),
            c.css()
        );
    }

    fn stroke_poly(&mut self, pts: &[[f64; 2]], c: Color, width: f64, close: bool) {
        let tag = if close { "polygon" } else { "polyline" };
        let _ = write!(
            self.out,
            "<{tag} points=\"{}\" fill=\"none\" stroke=\"{}\" stroke-width=\"{}\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n",
            Self::pts(pts),
            c.css(),
            f(width)
        );
    }

    fn polyline(&mut self, pts: &[[f64; 2]], c: Color, width: f64, dash: bool) {
        let dash_attr = if dash {
            " stroke-dasharray=\"4 3\""
        } else {
            ""
        };
        let _ = write!(
            self.out,
            "<polyline points=\"{}\" fill=\"none\" stroke=\"{}\" stroke-width=\"{}\" stroke-linecap=\"round\" stroke-linejoin=\"round\"{dash_attr}/>\n",
            Self::pts(pts),
            c.css(),
            f(width)
        );
    }

    fn line(&mut self, x0: f64, y0: f64, x1: f64, y1: f64, c: Color, width: f64) {
        let _ = write!(
            self.out,
            "<line x1=\"{}\" y1=\"{}\" x2=\"{}\" y2=\"{}\" stroke=\"{}\" stroke-width=\"{}\" stroke-linecap=\"round\"/>\n",
            f(x0),
            f(y0),
            f(x1),
            f(y1),
            c.css(),
            f(width)
        );
    }

    fn arc(&mut self, cx: f64, cy: f64, r: f64, a0: f64, a1: f64, c: Color, width: f64) {
        let pts = arc_pts(cx, cy, r, a0, a1);
        self.polyline(&pts, c, width, false);
    }

    fn text(&mut self, x: f64, y: f64, s: &str, size: f64, c: Color, align: Align) {
        if s.is_empty() {
            return;
        }
        let (anchor, baseline, dx) = match align {
            Align::TopLeft => ("start", "hanging", 0.0),
            Align::HCenter => ("middle", "hanging", 0.0),
            Align::Center => ("middle", "middle", 0.0),
            Align::Right => ("end", "hanging", 0.0),
        };
        let _ = write!(
            self.out,
            "<text x=\"{}\" y=\"{}\" font-size=\"{}\" font-family=\"Ubuntu, sans-serif\" fill=\"{}\" text-anchor=\"{anchor}\" dominant-baseline=\"{baseline}\"",
            f(x + dx),
            f(y),
            f(size),
            c.css()
        );
        let _ = write!(self.out, ">{}</text>\n", xml_escape(s));
    }

    fn text_bold(&mut self, x: f64, y: f64, s: &str, size: f64, c: Color, align: Align) {
        if s.is_empty() {
            return;
        }
        let (anchor, baseline, dx) = match align {
            Align::TopLeft => ("start", "hanging", 0.0),
            Align::HCenter => ("middle", "hanging", 0.0),
            Align::Center => ("middle", "middle", 0.0),
            Align::Right => ("end", "hanging", 0.0),
        };
        let _ = write!(
            self.out,
            "<text x=\"{}\" y=\"{}\" font-size=\"{}\" font-weight=\"bold\" font-family=\"Ubuntu, sans-serif\" fill=\"{}\" text-anchor=\"{anchor}\" dominant-baseline=\"{baseline}\"",
            f(x + dx),
            f(y),
            f(size),
            c.css()
        );
        let _ = write!(self.out, ">{}</text>\n", xml_escape(s));
    }

    fn grid_dots(&mut self, scene: Rect, step: i32, c: Color) {
        let step_u = 8 * step.max(1);
        let _ = write!(
            self.out,
            "<defs><pattern id=\"grid\" width=\"{w}\" height=\"{w}\" patternUnits=\"userSpaceOnUse\" x=\"4\" y=\"4\"><circle cx=\"0\" cy=\"0\" r=\"0.75\" fill=\"{fill}\"/></pattern></defs>\n",
            w = step_u,
            fill = c.css()
        );
        let _ = write!(
            self.out,
            "<rect x=\"{}\" y=\"{}\" width=\"{}\" height=\"{}\" fill=\"url(#grid)\"/>\n",
            f(scene.x),
            f(scene.y),
            f(scene.w),
            f(scene.h)
        );
    }

    fn push(&mut self, x: f64, y: f64, rot: f64, sx: f64, sy: f64) {
        let _ = write!(
            self.out,
            "<g transform=\"translate({},{}) rotate({}) scale({},{})\">\n",
            f(x),
            f(y),
            f(rot),
            f(sx),
            f(sy)
        );
    }

    fn pop(&mut self) {
        self.out.push_str("</g>\n");
    }

    fn push_clip_rect(&mut self, x: f64, y: f64, w: f64, h: f64) {
        let clip_id = format!("clip_{}", self.clip_count);
        self.clip_count += 1;
        let _ = write!(
            self.out,
            "<clipPath id=\"{clip_id}\"><rect x=\"{}\" y=\"{}\" width=\"{}\" height=\"{}\"/></clipPath>\n<g clip-path=\"url(#{clip_id})\">\n",
            f(x),
            f(y),
            f(w),
            f(h)
        );
        self.clip_stack.push(clip_id);
    }

    fn pop_clip(&mut self) {
        if self.clip_stack.pop().is_some() {
            self.out.push_str("</g>\n");
        }
    }

    fn draw_pixmap_rect(
        &mut self,
        x: f64,
        y: f64,
        w: f64,
        h: f64,
        pm: &tiny_skia::Pixmap,
        opacity: f64,
    ) -> bool {
        if pm.width() == 0 || pm.height() == 0 || w <= 0.0 || h <= 0.0 {
            return false;
        }
        if let Ok(png_bytes) = pm.encode_png() {
            let b64 = base64_encode(&png_bytes);
            let _ = write!(
                self.out,
                "<image x=\"{}\" y=\"{}\" width=\"{}\" height=\"{}\" opacity=\"{}\" href=\"data:image/png;base64,{}\"/>\n",
                f(x),
                f(y),
                f(w),
                f(h),
                f(opacity.clamp(0.0, 1.0)),
                b64
            );
            return true;
        }
        false
    }
}

fn base64_encode(bytes: &[u8]) -> String {
    const TABLE: &[u8; 64] = b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
    let mut out = String::with_capacity((bytes.len() + 2) / 3 * 4);
    for chunk in bytes.chunks(3) {
        let b0 = chunk[0];
        let b1 = if chunk.len() > 1 { chunk[1] } else { 0 };
        let b2 = if chunk.len() > 2 { chunk[2] } else { 0 };
        out.push(TABLE[(b0 >> 2) as usize] as char);
        out.push(TABLE[(((b0 & 0x03) << 4) | (b1 >> 4)) as usize] as char);
        if chunk.len() > 1 {
            out.push(TABLE[(((b1 & 0x0f) << 2) | (b2 >> 6)) as usize] as char);
        } else {
            out.push('=');
        }
        if chunk.len() > 2 {
            out.push(TABLE[(b2 & 0x3f) as usize] as char);
        } else {
            out.push('=');
        }
    }
    out
}
