use super::text::get_cached_glyph;
use super::*;
use crate::canvas::{Canvas, Scene};

fn tmp(name: &str) -> std::path::PathBuf {
    let mut p = std::env::temp_dir();
    p.push(format!("cs-export-{}-{name}", std::process::id()));
    p
}

#[test]
fn png_matches_view_size() {
    let c = Canvas::new();
    let (vw, vh) = c.viewport().view_size();
    let bytes = png_bytes(&c, &Palette::light()).unwrap();
    assert_eq!(&bytes[0..8], b"\x89PNG\r\n\x1a\n");
    let w = u32::from_be_bytes(bytes[16..20].try_into().unwrap());
    let h = u32::from_be_bytes(bytes[20..24].try_into().unwrap());
    assert_eq!(w, vw.round() as u32);
    assert_eq!(h, vh.round() as u32);
    assert!(bytes.len() > 200);
}

#[test]
fn svg_has_paper_wires_and_parts() {
    let c = Canvas::new();
    let svg = svg_string(&c, &Palette::light());
    assert!(svg.contains("<svg"));
    assert!(svg.contains("Generated by Circuit Simulator"));
    assert!(svg.contains("viewBox"));
    assert!(svg.contains("<rect") || svg.contains("<polyline"));
    assert!(svg.contains("url(#grid)") || svg.contains("<circle"));
}

#[test]
fn jpeg_bmp_svg_files() {
    let c = Canvas::new();
    let pal = Palette::light();
    for (name, magic) in [
        ("t.png", &b"\x89PNG"[..]),
        ("t.jpg", &b"\xff\xd8"[..]),
        ("t.bmp", &b"BM"[..]),
    ] {
        let path = tmp(name);
        save_image(&c, &path, &pal).unwrap();
        let data = std::fs::read(&path).unwrap();
        assert!(
            data.starts_with(magic),
            "{name} {:?}",
            &data[..data.len().min(4)]
        );
        let _ = std::fs::remove_file(&path);
    }
    let path = tmp("t.svg");
    save_image(&c, &path, &pal).unwrap();
    let s = std::fs::read_to_string(&path).unwrap();
    assert!(s.contains("<svg"));
    let _ = std::fs::remove_file(&path);
}

#[test]
fn hex_palette_alpha() {
    let c = parse_hex("#2832464b");
    assert_eq!(c.r, 0x28);
    assert_eq!(c.a, 0x4b);
    let d = parse_hex("#f5f8fa");
    assert_eq!(d.g, 0xf8);
    assert_eq!(d.a, 255);
}

#[test]
fn render_viewport_with_selection() {
    use crate::canvas::scene::Item;
    let mut c = Canvas::new();
    c.scene_mut()
        .add_saved_item(Item::fixed_volt("FV-1", 100.0, 100.0, 5.0));
    c.scene_mut()
        .add_saved_item(Item::resistor("R-1", 200.0, 100.0, 1000.0));
    let pal = Palette::light();
    let pm = render_viewport(&c, &pal, 400, 300, 1.0, true).unwrap();
    assert_eq!(pm.width(), 400);
    assert_eq!(pm.height(), 300);

    c.select_all();
    let pm_sel = render_viewport(&c, &pal, 400, 300, 1.0, true).unwrap();
    assert_eq!(pm_sel.width(), 400);
    assert_eq!(pm_sel.height(), 300);
    assert_ne!(pm.data(), pm_sel.data());
}

#[test]
fn render_viewport_regions_patches_without_full_clear() {
    use crate::canvas::scene::Item;
    let mut c = Canvas::new();
    c.set_view_size(400.0, 300.0);
    c.scene_mut()
        .add_saved_item(Item::fixed_volt("FV-1", 40.0, 40.0, 5.0));
    c.scene_mut()
        .add_saved_item(Item::resistor("R-1", 200.0, 150.0, 1000.0));
    let pal = Palette::light();
    let mut pm = render_viewport(&c, &pal, 400, 300, 1.0, true).unwrap();
    let before = pm.data().to_vec();
    let r1 = c
        .scene()
        .item_by_id("R-1")
        .unwrap()
        .total_bounding_rect()
        .adjust(-4.0, -4.0, 4.0, 4.0);
    assert!(render_viewport_regions_mut(&c, &pal, &mut pm, 1.0, &[r1]));
    // Scene did not change, so a region blit of the same content must keep
    // pixels outside the resistor's neighbourhood identical.
    let after = pm.data();
    let mut same = 0usize;
    let mut diff = 0usize;
    for (a, b) in before.iter().zip(after.iter()) {
        if a == b {
            same += 1;
        } else {
            diff += 1;
        }
    }
    assert!(same > 0);
    assert!(
        diff < same / 2,
        "region raster rewrote too much of the pixmap (same={same} diff={diff})"
    );
}

#[test]
fn test_glyph_cache_retrieval() {
    let g1 = get_cached_glyph(false, 'A', 12.0);
    let g2 = get_cached_glyph(false, 'A', 12.0);
    assert_eq!(g1.metrics.advance_width, g2.metrics.advance_width);
    assert_eq!(g1.metrics.width, g2.metrics.width);
    assert_eq!(g1.metrics.height, g2.metrics.height);
    assert_eq!(g1.bitmap.len(), g2.bitmap.len());

    let g_bold = get_cached_glyph(true, 'A', 12.0);
    assert!(!g_bold.bitmap.is_empty());
}

#[test]
fn test_connected_pins_set_and_wire_bounds() {
    use crate::canvas::geom::Point;
    use crate::canvas::wire::Wire;

    let w = Wire::from_saved(
        "w1",
        "push1-lPin0",
        "r1-rPin",
        vec![Point::new(10.0, 20.0), Point::new(50.0, 80.0)],
    );
    let bounds = w.bounding_rect();
    assert_eq!(bounds.x, 10.0);
    assert_eq!(bounds.y, 20.0);
    assert_eq!(bounds.w, 40.0);
    assert_eq!(bounds.h, 60.0);

    let mut scene = Scene::new();
    scene.add_saved_wire(w);
    let connected = scene.connected_pins_set();
    assert!(connected.contains("push1-lPin0"));
    assert!(connected.contains("r1-rPin"));
}

#[test]
fn test_pins_painted_before_component_body() {
    use crate::canvas::draw::{Align, Color, Draw, PaintCtx};
    use crate::canvas::scene::Item;

    #[derive(Default)]
    struct CallRecorder {
        calls: Vec<String>,
    }

    impl Draw for CallRecorder {
        fn fill_rect(&mut self, _x: f64, _y: f64, _w: f64, _h: f64, _c: Color) {
            self.calls.push("fill_rect".into());
        }
        fn stroke_rect(&mut self, _x: f64, _y: f64, _w: f64, _h: f64, _c: Color, _width: f64) {
            self.calls.push("stroke_rect".into());
        }
        fn fill_round_rect(&mut self, _x: f64, _y: f64, _w: f64, _h: f64, _r: f64, _c: Color) {
            self.calls.push("fill_round_rect".into());
        }
        fn stroke_round_rect(
            &mut self,
            _x: f64,
            _y: f64,
            _w: f64,
            _h: f64,
            _r: f64,
            _c: Color,
            _width: f64,
        ) {
            self.calls.push("stroke_round_rect".into());
        }
        fn fill_circle(&mut self, _cx: f64, _cy: f64, _r: f64, _c: Color) {
            self.calls.push("fill_circle".into());
        }
        fn stroke_circle(&mut self, _cx: f64, _cy: f64, _r: f64, _c: Color, _width: f64) {
            self.calls.push("stroke_circle".into());
        }
        fn fill_ellipse(&mut self, _x: f64, _y: f64, _w: f64, _h: f64, _c: Color) {
            self.calls.push("fill_ellipse".into());
        }
        fn stroke_ellipse(&mut self, _x: f64, _y: f64, _w: f64, _h: f64, _c: Color, _width: f64) {
            self.calls.push("stroke_ellipse".into());
        }
        fn fill_poly(&mut self, _pts: &[[f64; 2]], _c: Color) {
            self.calls.push("fill_poly".into());
        }
        fn stroke_poly(&mut self, _pts: &[[f64; 2]], _c: Color, _width: f64, _close: bool) {
            self.calls.push("stroke_poly".into());
        }
        fn polyline(&mut self, _pts: &[[f64; 2]], _c: Color, _width: f64, _dash: bool) {
            self.calls.push("polyline".into());
        }
        fn line(&mut self, _x0: f64, _y0: f64, _x1: f64, _y1: f64, _c: Color, _width: f64) {
            self.calls.push("line".into());
        }
        fn arc(&mut self, _cx: f64, _cy: f64, _r: f64, _a0: f64, _a1: f64, _c: Color, _width: f64) {
            self.calls.push("arc".into());
        }
        fn text(&mut self, _x: f64, _y: f64, _s: &str, _size: f64, _c: Color, _align: Align) {
            self.calls.push("text".into());
        }
        fn grid_dots(&mut self, _scene: Rect, _step: i32, _c: Color) {
            self.calls.push("grid_dots".into());
        }
        fn push(&mut self, _x: f64, _y: f64, _rot: f64, _sx: f64, _sy: f64) {
            self.calls.push("push".into());
        }
        fn pop(&mut self) {
            self.calls.push("pop".into());
        }
    }

    let c = Canvas::new();
    let pal = Palette::light();
    let ctx = PaintCtx {
        canvas: &c,
        pal: &pal,
        scale: 1.0,
        item_id: "R-1",
    };
    let item = Item::resistor("R-1", 100.0, 100.0, 1000.0);
    let mut rec = CallRecorder::default();
    let connected = rustc_hash::FxHashSet::default();
    paint_item(&mut rec, &ctx, c.scene(), &item, &connected);

    // Resistor has 2 pins. Each unconnected pin pushes transform, fill_rect for stem, stroke_circle for tip, pop.
    // The resistor body stroke_rect must occur AFTER the pins are drawn.
    let stroke_rect_idx = rec
        .calls
        .iter()
        .position(|call| call == "stroke_rect")
        .expect("should stroke resistor border");
    // Pin stems are drawn with fill_rect before the body's stroke_rect
    assert!(
        stroke_rect_idx > 4,
        "stroke_rect should occur after pin rendering; calls: {:?}",
        rec.calls
    );
}

#[test]
fn test_current_animation_chevron_geometry() {
    use crate::canvas::Point;
    use crate::canvas::draw::{Align, Color, Draw};
    use crate::canvas::export::paint::paint_chevrons;
    use crate::theme::WIRE_WIDTH;

    #[derive(Default)]
    struct PolyRecorder {
        polylines: Vec<(Vec<[f64; 2]>, f64)>,
    }

    impl Draw for PolyRecorder {
        fn fill_rect(&mut self, _x: f64, _y: f64, _w: f64, _h: f64, _c: Color) {}
        fn stroke_rect(&mut self, _x: f64, _y: f64, _w: f64, _h: f64, _c: Color, _width: f64) {}
        fn fill_round_rect(&mut self, _x: f64, _y: f64, _w: f64, _h: f64, _r: f64, _c: Color) {}
        fn stroke_round_rect(
            &mut self,
            _x: f64,
            _y: f64,
            _w: f64,
            _h: f64,
            _r: f64,
            _c: Color,
            _width: f64,
        ) {
        }
        fn fill_circle(&mut self, _cx: f64, _cy: f64, _r: f64, _c: Color) {}
        fn stroke_circle(&mut self, _cx: f64, _cy: f64, _r: f64, _c: Color, _width: f64) {}
        fn fill_ellipse(&mut self, _x: f64, _y: f64, _w: f64, _h: f64, _c: Color) {}
        fn stroke_ellipse(&mut self, _x: f64, _y: f64, _w: f64, _h: f64, _c: Color, _width: f64) {}
        fn fill_poly(&mut self, _pts: &[[f64; 2]], _c: Color) {}
        fn stroke_poly(&mut self, _pts: &[[f64; 2]], _c: Color, _width: f64, _close: bool) {}
        fn polyline(&mut self, pts: &[[f64; 2]], _c: Color, width: f64, _dash: bool) {
            self.polylines.push((pts.to_vec(), width));
        }
        fn line(&mut self, _x0: f64, _y0: f64, _x1: f64, _y1: f64, _c: Color, _width: f64) {}
        fn arc(&mut self, _cx: f64, _cy: f64, _r: f64, _a0: f64, _a1: f64, _c: Color, _width: f64) {
        }
        fn text(&mut self, _x: f64, _y: f64, _s: &str, _size: f64, _c: Color, _align: Align) {}
        fn grid_dots(&mut self, _scene: Rect, _step: i32, _c: Color) {}
        fn push(&mut self, _x: f64, _y: f64, _rot: f64, _sx: f64, _sy: f64) {}
        fn pop(&mut self) {}
    }

    let mut rec = PolyRecorder::default();
    let pts = [Point::new(0.0, 10.0), Point::new(50.0, 10.0)];
    paint_chevrons(&mut rec, &pts, 1.0, 0.0, Color::rgb(0, 0, 0));

    assert!(!rec.polylines.is_empty(), "must draw at least one chevron");
    for (poly, width) in &rec.polylines {
        assert_eq!(poly.len(), 3, "chevron must have 3 points");
        assert_eq!(*width, WIRE_WIDTH, "chevron width must match WIRE_WIDTH");

        let wing1 = poly[0];
        let tip = poly[1];
        let wing2 = poly[2];

        // For horizontal rightwards wire at y = 10.0:
        // Tip should be 1.0 ahead of center along x, wings 1.0 behind center along x -> depth 2.0
        let depth = tip[0] - wing1[0];
        assert!(
            (depth - 2.0).abs() < 1e-6,
            "depth along wire must be 2.0 (same as pin arrow depth)"
        );
        assert!(
            (wing1[0] - wing2[0]).abs() < 1e-6,
            "wing x coordinates must be equal"
        );

        // Wings span perpendicular by ±2.0 from centerline y = 10.0
        let wing_span = (wing1[1] - wing2[1]).abs();
        assert!(
            (wing_span - 4.0).abs() < 1e-6,
            "total wing span must be 4.0 (±2.0 from centerline)"
        );

        // Line angle: dx = 2.0, dy = 2.0 -> 45 degrees
        let d_wing1_x = tip[0] - wing1[0];
        let d_wing1_y = tip[1] - wing1[1];
        assert!(
            (d_wing1_x.abs() - d_wing1_y.abs()).abs() < 1e-6,
            "line angle must be 45 degrees (equal dx and dy)"
        );
    }
}

#[test]
fn test_current_animation_chevrons_fade_in_and_out() {
    use crate::canvas::Point;
    use crate::canvas::draw::{Align, Color, Draw};
    use crate::canvas::export::paint::paint_chevrons;

    #[derive(Default)]
    struct AlphaRecorder {
        alphas: Vec<u8>,
    }

    impl Draw for AlphaRecorder {
        fn fill_rect(&mut self, _x: f64, _y: f64, _w: f64, _h: f64, _c: Color) {}
        fn stroke_rect(&mut self, _x: f64, _y: f64, _w: f64, _h: f64, _c: Color, _width: f64) {}
        fn fill_round_rect(&mut self, _x: f64, _y: f64, _w: f64, _h: f64, _r: f64, _c: Color) {}
        fn stroke_round_rect(
            &mut self,
            _x: f64,
            _y: f64,
            _w: f64,
            _h: f64,
            _r: f64,
            _c: Color,
            _width: f64,
        ) {
        }
        fn fill_circle(&mut self, _cx: f64, _cy: f64, _r: f64, _c: Color) {}
        fn stroke_circle(&mut self, _cx: f64, _cy: f64, _r: f64, _c: Color, _width: f64) {}
        fn fill_ellipse(&mut self, _x: f64, _y: f64, _w: f64, _h: f64, _c: Color) {}
        fn stroke_ellipse(&mut self, _x: f64, _y: f64, _w: f64, _h: f64, _c: Color, _width: f64) {}
        fn fill_poly(&mut self, _pts: &[[f64; 2]], _c: Color) {}
        fn stroke_poly(&mut self, _pts: &[[f64; 2]], _c: Color, _width: f64, _close: bool) {}
        fn polyline(&mut self, pts: &[[f64; 2]], c: Color, _width: f64, _dash: bool) {
            if pts.len() == 3 {
                self.alphas.push(c.a);
            }
        }
        fn line(&mut self, _x0: f64, _y0: f64, _x1: f64, _y1: f64, _c: Color, _width: f64) {}
        fn arc(&mut self, _cx: f64, _cy: f64, _r: f64, _a0: f64, _a1: f64, _c: Color, _width: f64) {
        }
        fn text(&mut self, _x: f64, _y: f64, _s: &str, _size: f64, _c: Color, _align: Align) {}
        fn grid_dots(&mut self, _scene: Rect, _step: i32, _c: Color) {}
        fn push(&mut self, _x: f64, _y: f64, _rot: f64, _sx: f64, _sy: f64) {}
        fn pop(&mut self) {}
    }

    let pts = [Point::new(0.0, 10.0), Point::new(50.0, 10.0)];
    let color = Color::rgb(0, 0, 0);

    let mut entering = AlphaRecorder::default();
    paint_chevrons(&mut entering, &pts, 1.0, 0.2, color);
    assert!(
        entering.alphas.len() >= 3,
        "need first, middle, last chevrons"
    );
    let first_a = entering.alphas[0];
    let mid_a = entering.alphas[1];
    assert!(
        first_a < mid_a,
        "chevron entering at the start must fade in; first={first_a} mid={mid_a}"
    );

    let mut later = AlphaRecorder::default();
    paint_chevrons(&mut later, &pts, 1.0, 2.8, color);
    assert!(
        later.alphas[0] > first_a,
        "further along the fade-in the first chevron must be more opaque"
    );

    let mut leaving = AlphaRecorder::default();
    paint_chevrons(&mut leaving, &pts, 1.0, 1.9, color);
    let last = leaving.alphas.len() - 1;
    let last_a = leaving.alphas[last];
    let mid_leave = leaving.alphas[1];
    assert!(
        last_a < mid_leave,
        "chevron leaving at the end must fade out; last={last_a} mid={mid_leave}"
    );
}

#[test]
fn test_current_animation_chevrons_drawn_on_top_of_everything() {
    use crate::canvas::Point;
    use crate::canvas::draw::{Align, Color, Draw, PaintCtx};
    use crate::canvas::export::paint::paint_scene;
    use crate::canvas::scene::Item;
    use crate::canvas::wire::Wire;

    #[derive(Default)]
    struct OrderRecorder {
        calls: Vec<String>,
    }

    impl Draw for OrderRecorder {
        fn fill_rect(&mut self, _x: f64, _y: f64, _w: f64, _h: f64, _c: Color) {
            self.calls.push("fill_rect".into());
        }
        fn stroke_rect(&mut self, _x: f64, _y: f64, _w: f64, _h: f64, _c: Color, _width: f64) {
            self.calls.push("stroke_rect".into());
        }
        fn fill_round_rect(&mut self, _x: f64, _y: f64, _w: f64, _h: f64, _r: f64, _c: Color) {
            self.calls.push("fill_round_rect".into());
        }
        fn stroke_round_rect(
            &mut self,
            _x: f64,
            _y: f64,
            _w: f64,
            _h: f64,
            _r: f64,
            _c: Color,
            _width: f64,
        ) {
            self.calls.push("stroke_round_rect".into());
        }
        fn fill_circle(&mut self, _cx: f64, _cy: f64, _r: f64, _c: Color) {
            self.calls.push("fill_circle".into());
        }
        fn stroke_circle(&mut self, _cx: f64, _cy: f64, _r: f64, _c: Color, _width: f64) {
            self.calls.push("stroke_circle".into());
        }
        fn fill_ellipse(&mut self, _x: f64, _y: f64, _w: f64, _h: f64, _c: Color) {
            self.calls.push("fill_ellipse".into());
        }
        fn stroke_ellipse(&mut self, _x: f64, _y: f64, _w: f64, _h: f64, _c: Color, _width: f64) {
            self.calls.push("stroke_ellipse".into());
        }
        fn fill_poly(&mut self, _pts: &[[f64; 2]], _c: Color) {
            self.calls.push("fill_poly".into());
        }
        fn stroke_poly(&mut self, _pts: &[[f64; 2]], _c: Color, _width: f64, _close: bool) {
            self.calls.push("stroke_poly".into());
        }
        fn polyline(&mut self, pts: &[[f64; 2]], _c: Color, _width: f64, _dash: bool) {
            if pts.len() == 3 {
                self.calls.push("chevron_polyline".into());
            } else {
                self.calls.push("wire_polyline".into());
            }
        }
        fn line(&mut self, _x0: f64, _y0: f64, _x1: f64, _y1: f64, _c: Color, _width: f64) {
            self.calls.push("line".into());
        }
        fn arc(&mut self, _cx: f64, _cy: f64, _r: f64, _a0: f64, _a1: f64, _c: Color, _width: f64) {
            self.calls.push("arc".into());
        }
        fn text(&mut self, _x: f64, _y: f64, _s: &str, _size: f64, _c: Color, _align: Align) {
            self.calls.push("text".into());
        }
        fn grid_dots(&mut self, _scene: Rect, _step: i32, _c: Color) {
            self.calls.push("grid_dots".into());
        }
        fn push(&mut self, _x: f64, _y: f64, _rot: f64, _sx: f64, _sy: f64) {
            self.calls.push("push".into());
        }
        fn pop(&mut self) {
            self.calls.push("pop".into());
        }
    }

    let mut c = Canvas::new();
    c.set_sim_running(true);
    c.update_circ_settings(|s| s.animate_curr = true);

    let w = Wire::from_saved(
        "W-1",
        "R-1-0",
        "R-2-0",
        vec![Point::new(0.0, 10.0), Point::new(100.0, 10.0)],
    );
    c.scene_mut().add_saved_wire(w);
    c.scene_mut()
        .add_saved_item(Item::resistor("R-1", 0.0, 10.0, 1000.0));
    c.scene_mut()
        .add_saved_item(Item::resistor("R-2", 100.0, 10.0, 1000.0));
    c.wire_currents.insert("W-1".into(), 0.02);

    let pal = Palette::light();
    let ctx = PaintCtx {
        canvas: &c,
        pal: &pal,
        scale: 1.0,
        item_id: "",
    };

    let mut rec = OrderRecorder::default();
    paint_scene(&mut rec, &ctx);

    let wire_idx = rec
        .calls
        .iter()
        .position(|call| call == "wire_polyline")
        .expect("should draw wire");
    let item_rect_idx = rec
        .calls
        .iter()
        .rposition(|call| call == "stroke_rect")
        .expect("should stroke item resistor body");
    let chevron_idx = rec
        .calls
        .iter()
        .position(|call| call == "chevron_polyline")
        .expect("should draw chevron");

    assert!(
        item_rect_idx > wire_idx,
        "items must be drawn after wire base line"
    );
    assert!(
        chevron_idx > item_rect_idx,
        "chevrons must be drawn after all items, at the top of everything; calls: {:?}",
        rec.calls
    );
}
